prometheus:
  prometheusSpec:
    retention: 30d

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: ebs-sc
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 3Gi

grafana:
  persistence:
    enabled: true
    type: sts
    storageClassName: ebs-sc
    accessModes:
      - ReadWriteOnce
    size: 1Gi
