apiVersion: v1
kind: Service
metadata:
  name: agent-nodeport
  namespace: prod
  labels:
    app: agent
spec:
  type: NodePort
  selector:
    app: agent
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 31800
      protocol: TCP
